config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:new, :create]
  end
  delete "doses/:id", to: "doses#destroy", as: 'dose'
  root to: "cocktails#index"
  mount Attachinary::Engine => "/attachinary"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
  has_attachment :photo

end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :ingredient, uniqueness: { scope: :cocktail,
    message: "this ingredient is already used for this cocktail" }

end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  private
  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)

  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktails_path
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<% content_for(:title_tag) do %>
  Index
<% end %>

<div class="container">
  <h1 class="text-center">Bruno's cocktails</h1>
  <hr>
  <div class="row">
    <% @cocktails.each do |cocktail| %>
    <div class="col-xs-12 col-sm-4">
      <% if cocktail.photo? %>
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path cocktail.photo.path, height: 300, width: 400, crop: :fill %>');">
          <div class="card-description">
            <h2><%= cocktail.name %></h2>
          </div>
          <%= link_to "", cocktail_path(cocktail), class: "card-link" %>
        </div>
      <% else %>
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= image_path('cocktails.jpg') %>');">
          <div class="card-description">
            <h2><%= cocktail.name %></h2>
          </div>
          <%= link_to "", cocktail_path(cocktail), class: "card-link" %>
        </div>
      <% end %>
    </div>

    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<% content_for(:title_tag) do %>
  New Cocktail
<% end %>

<div class="container">
  <%= simple_form_for(@cocktail) do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :attachinary %>
    <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/cocktails/show.html.erb
<% content_for(:title_tag) do %>
  <%= @cocktail.name %>
<% end %>

<h1>Cocktails#show</h1>
<% if @cocktail.photo? %>
  <%= cl_image_tag @cocktail.photo.path, width: 200, height: 300, crop: :fill %>
<% end %>
<ul>
  <li>
    <p>
      <strong>Name: </strong>
      <%= @cocktail.name %>
    </p>
  </li>
  <li>
    <p><strong>Ingredients: </strong></p>
    <ul>
      <% @cocktail.ingredients.each do |ingredient| %>
        <% dose = Dose.where(cocktail: @cocktail, ingredient: ingredient)[0] %>
        <li><%= ingredient.name %> - dose: <%= dose.description %> - <%= link_to "delete dose", dose_path(dose), method: :delete %></li>
      <% end %>
    </ul>
  </li>
  <li>
    <%= link_to "add ingredient", new_cocktail_dose_path(@cocktail) %>
  </li>
  <li>
    <%= link_to "Index", cocktails_path %>
  </li>
</ul>

app/views/doses/new.html.erb
<% content_for(:title_tag) do %>
  Add ingredient
<% end %>

<div class="container">
  <h2>Add a dose for <%= @cocktail.name %></h2>
  <%= simple_form_for [@cocktail, @dose] do |f| %>
    <%= f.association :ingredient %>
    <%= f.input :description %>
    <%= @dose.errors.messages[:cocktail][0] if @dose.errors.messages[:cocktail][0] %>
    <%= f.submit "add a dose", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      <%= yield(:title_tag).blank? ? "Bruno's Cocktails" : yield(:title_tag) %>
    </title>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'%>
    <%= cloudinary_js_config %>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <!-- Add these line for detecting device width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->

  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "icon.ico" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search your cocktail">
    </form>

    <!-- Text link -->
    <a href="" class="navbar-wagon-item navbar-wagon-link">About</a>

    <!-- Button (call-to-action) -->
    <%= link_to "Create a cocktail!", new_cocktail_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

</div>